Add short script to move vendor folder around
**What**
- Add Dockerfile testp to mov ethe vendor folder up from the function
  volder to function root. This allows the user to control the vendor
  folder and avoid collisions/validation errors from Go in modules mode
- This new flow allows dynamic downloading of Go modules _or_ disabling
  Go modules and only using vendor. You can not use vendor _and_ modules
  at the same time due to how Go will validate that the vendor folder
  and the go.mod are insync

Signed-off-by: Lucas Roesler <roesler.lucas@gmail.com>

diff --git a/template/golang-middleware/Dockerfile b/template/golang-middleware/Dockerfile
--- a/template/golang-middleware/Dockerfile
+++ b/template/golang-middleware/Dockerfile
@@ -17,15 +17,21 @@ RUN mkdir -p /go/src/handler
 WORKDIR /go/src/handler
 COPY . .
 
-# Add user overrides to the root go.mod, which is the only place "replace" can be used
-RUN cat function/GO_REPLACE.txt >> ./go.mod || exit 0
-
-# Run a gofmt and exclude all vendored code.
-RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
-
 ARG GO111MODULE="off"
 ARG GOPROXY=""
 ARG GOFLAGS=""
+
+# Add user overrides to the root go.mod, which is the only place "replace" can be used
+RUN cat function/GO_REPLACE.txt >> ./go.mod || exit 0
+RUN if [ -d ./function/vendor ] && [ "${GO111MODULE}" == "off" ]; then \
+    echo "moving handler vendor" && \
+    mv -f ./function/vendor .; \
+    else \
+    echo "using modules or vendor not found "; \
+    fi
+
+# Run a gofmt and exclude all vendored code.
+RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
 
 WORKDIR /go/src/handler/function
 
@@ -39,7 +45,7 @@ FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:3.13
 # Add non root user and certs
 RUN apk --no-cache add ca-certificates \
     && addgroup -S app && adduser -S -g app app
-# Split instructions so that buildkit can run & cache 
+# Split instructions so that buildkit can run & cache
 # the previous command ahead of time.
 RUN mkdir -p /home/app \
     && chown app /home/app
